# -*- coding: utf-8 -*-
"""DPSOFIM_Gradient.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19iJaP-j2d8Q0u6Z26sybVgjcUsOTE3n9
"""

from google.colab import drive
drive.mount('/content/drive')
!pip install -q optuna torch torchvision

!pip install medmnist

"""# **Checking Pipeline**"""

# Commented out IPython magic to ensure Python compatibility.
# Run the full sweep (SOFIM + Baselines)
# %cd /content/drive/MyDrive/DP-FedGD
!python run_dp_fedgd_experiments.py

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/DP-FedGD
import os
import json
import matplotlib.pyplot as plt
import numpy as np

# --- Configuration ---
# Must match the directory in the runner script
results_dir = "./fedgd_clients20_path"
epsilons = [0]
rounds_list = [1, 2, 5, 10, 20, 30, 40, 50, 60, 70]

# Containers
all_accuracies = {}
all_losses = {}

print(f"Reading results from: {results_dir}")

for eps in epsilons:
    accuracies, losses = [], []

    for rounds in rounds_list:
        path = os.path.join(results_dir, f"fedgd_eps{eps}_rounds{rounds}.json")

        if not os.path.exists(path):
            print(f"  Missing file: {path}")
            accuracies.append(None)
            losses.append(None)
            continue

        try:
            with open(path, "r") as f:
                data = json.load(f)

            # Extract metrics (handle potential missing keys)
            final_stats = data.get("final_stats", {})
            acc = final_stats.get("accuracy", None)
            loss = final_stats.get("loss", None)

            if acc is None:
                print(f"  Warning: No accuracy found in {path}")

            accuracies.append(acc)
            losses.append(loss)

        except json.JSONDecodeError:
            print(f"  Error: Could not decode JSON {path}")
            accuracies.append(None)
            losses.append(None)

    all_accuracies[eps] = accuracies
    all_losses[eps] = losses

# --- Plotting Helper ---
def plot_metric(metric_dict, metric_name, filename):
    plt.figure(figsize=(8, 6))

    # Color map for distinct lines
    colors = plt.cm.viridis(np.linspace(0, 1, len(metric_dict)))

    for (eps, values), color in zip(metric_dict.items(), colors):
        # Filter out Nones for plotting
        valid_rounds = [r for r, v in zip(rounds_list, values) if v is not None]
        valid_values = [v for v in values if v is not None]

        if valid_values:
            plt.plot(valid_rounds, valid_values, marker="o", linestyle='-',
                     linewidth=2, markersize=6, label=f"ε = {eps}", color=color)
            for x, y in zip(valid_rounds, valid_values):
                # Formatting: 4 decimal places for accuracy, 2 for loss
                label_text = f"{y:.4f}" if metric_name == "Accuracy" else f"{y:.2f}"

                # Use annotate instead of text to support offsets
                plt.annotate(
                    label_text,
                    xy=(x, y),         # The point to annotate
                    fontsize=9,
                    fontweight='bold',
                    ha='center',       # horizontal alignment
                    va='bottom',       # vertical alignment
                    xytext=(0, 10),    # 10 point vertical offset
                    textcoords='offset points'
                )

    plt.title(f"DP-fedgd CIFAR-10 (ResNet20): {metric_name} vs Rounds")
    plt.xlabel("Federated Rounds")
    plt.ylabel(f"Test {metric_name}")
    plt.xticks(rounds_list)
    plt.grid(True, linestyle="--", alpha=0.4)
    plt.legend(title="Privacy Budget")
    plt.tight_layout()

    # Save and Show
    plt.savefig(filename, dpi=300)
    print(f"Saved plot to {filename}")
    plt.show()

# Generate Plots

plot_metric(all_accuracies, "Accuracy", "dp_sofim_accuracy_curve.png")


plot_metric(all_losses, "Loss", "dp_sofim_loss_curve.png")

# Commented out IPython magic to ensure Python compatibility.
# Run the full sweep (SOFIM + Baselines)
# %cd /content/drive/MyDrive/DP-FedGD
!python plot_comparison.py

import os
import json
import glob

def diagnose_results_files():
    """
    Diagnostic script to see exactly what files exist and what data they contain.
    """

    alg_dirs = {
        "fedgd": "./results_sweep_fedgd_clients100",
        "sofim": "./results_sweep_sofim_clients100"
    }

    print("="*80)
    print("DIAGNOSTIC: Checking all result files")
    print("="*80)

    for alg, results_dir in alg_dirs.items():
        print(f"\n{'='*80}")
        print(f"Algorithm: {alg.upper()}")
        print(f"Directory: {results_dir}")
        print(f"{'='*80}")

        if not os.path.exists(results_dir):
            print(f"❌ DIRECTORY NOT FOUND: {results_dir}")
            continue

        pattern = os.path.join(results_dir, "*.json")
        files = sorted(glob.glob(pattern))

        print(f"\nFound {len(files)} JSON files\n")

        for i, filepath in enumerate(files, 1):
            filename = os.path.basename(filepath)
            print(f"\n{'-'*80}")
            print(f"File {i}: {filename}")
            print(f"{'-'*80}")

            try:
                with open(filepath, "r") as f:
                    data = json.load(f)

                # Extract config info
                config = data.get("config", {})
                sweep_cfg = data.get("sweep_config", {})

                epsilon = sweep_cfg.get("epsilon") or config.get("epsilon")
                rounds = sweep_cfg.get("rounds") or config.get("federated_rounds")

                print(f"  Config epsilon: {epsilon}")
                print(f"  Config rounds: {rounds}")

                # Extract round results
                rr = data.get("round_results", []) or data.get("results", {}).get("round_results", [])

                if not rr:
                    print(f"  ⚠️  NO ROUND RESULTS FOUND")
                    continue

                print(f"  Total round entries: {len(rr)}")

                # Check what rounds have data
                rounds_with_data = []
                for r in rr:
                    round_num = r.get("round")
                    if round_num is not None:
                        rounds_with_data.append(round_num)

                if rounds_with_data:
                    print(f"  Rounds with data: {sorted(rounds_with_data)}")
                    print(f"  First round: {min(rounds_with_data)}")
                    print(f"  Last round: {max(rounds_with_data)}")
                else:
                    print(f"  ⚠️  No 'round' field found in round_results")

                # Check for accuracy keys
                acc_keys_found = set()
                for r in rr:
                    for key in ["accuracy", "test_accuracy", "acc", "test_acc"]:
                        if key in r and r[key] is not None:
                            acc_keys_found.add(key)

                if acc_keys_found:
                    print(f"  Accuracy keys found: {acc_keys_found}")

                    # Show first 5 rounds with accuracy
                    print(f"\n  First 5 rounds with accuracy:")
                    count = 0
                    for r in rr:
                        round_num = r.get("round")
                        for key in acc_keys_found:
                            acc = r.get(key)
                            if round_num is not None and acc is not None:
                                print(f"    Round {round_num}: {key}={acc:.4f}")
                                count += 1
                                break
                        if count >= 5:
                            break
                else:
                    print(f"  ❌ NO ACCURACY DATA FOUND")
                    print(f"  Available keys in round_results[0]: {list(rr[0].keys()) if rr else 'N/A'}")

            except json.JSONDecodeError as e:
                print(f"  ❌ JSON DECODE ERROR: {e}")
            except Exception as e:
                print(f"  ❌ ERROR: {e}")

    print(f"\n{'='*80}")
    print("DIAGNOSIS COMPLETE")
    print(f"{'='*80}\n")


if __name__ == "__main__":
    diagnose_results_files()

"""MEDICAL DATASET"""

!pip install medmnist

# Commented out IPython magic to ensure Python compatibility.
# Run the full sweep (SOFIM + Baselines)
# %cd /content/drive/MyDrive/DP-FedGD
!python run_dp_fedgd_experiments.py

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/DP-FedGD
import os
import json
import matplotlib.pyplot as plt
import numpy as np

# --- Configuration ---
# Must match the directory in the runner script
results_dir = "./results_sweep_sofim_medical"
epsilons = [0.5]
rounds_list = [1, 2, 5, 10, 20, 30, 40, 50, 60, 70]

# Containers
all_accuracies = {}
all_losses = {}

print(f"Reading results from: {results_dir}")

for eps in epsilons:
    accuracies, losses = [], []

    for rounds in rounds_list:
        path = os.path.join(results_dir, f"sofim_eps{eps}_rounds{rounds}.json")

        if not os.path.exists(path):
            print(f"  Missing file: {path}")
            accuracies.append(None)
            losses.append(None)
            continue

        try:
            with open(path, "r") as f:
                data = json.load(f)

            # Extract metrics (handle potential missing keys)
            final_stats = data.get("final_stats", {})
            acc = final_stats.get("accuracy", None)
            loss = final_stats.get("loss", None)

            if acc is None:
                print(f"  Warning: No accuracy found in {path}")

            accuracies.append(acc)
            losses.append(loss)

        except json.JSONDecodeError:
            print(f"  Error: Could not decode JSON {path}")
            accuracies.append(None)
            losses.append(None)

    all_accuracies[eps] = accuracies
    all_losses[eps] = losses

# --- Plotting Helper ---
def plot_metric(metric_dict, metric_name, filename):
    plt.figure(figsize=(8, 6))

    # Color map for distinct lines
    colors = plt.cm.viridis(np.linspace(0, 1, len(metric_dict)))

    for (eps, values), color in zip(metric_dict.items(), colors):
        # Filter out Nones for plotting
        valid_rounds = [r for r, v in zip(rounds_list, values) if v is not None]
        valid_values = [v for v in values if v is not None]

        if valid_values:
            plt.plot(valid_rounds, valid_values, marker="o", linestyle='-',
                     linewidth=2, markersize=6, label=f"ε = {eps}", color=color)

    plt.title(f"DP-fedgd CIFAR-10 (ResNet20): {metric_name} vs Rounds")
    plt.xlabel("Federated Rounds")
    plt.ylabel(f"Test {metric_name}")
    plt.xticks(rounds_list)
    plt.grid(True, linestyle="--", alpha=0.4)
    plt.legend(title="Privacy Budget")
    plt.tight_layout()

    # Save and Show
    plt.savefig(filename, dpi=300)
    print(f"Saved plot to {filename}")
    plt.show()

# Generate Plots

plot_metric(all_accuracies, "Accuracy", "dp_sofim_accuracy_curve.png")


plot_metric(all_losses, "Loss", "dp_sofim_loss_curve.png")